### ISSUE TITLE
How About Real Time Style Transfer?

### ISSUE THREAD

**Issue by lucasjinreal** [LouieYang/deep-photo-styletransfer-tf#1]
Seems this code has a lot of setup things to work with such as segmentation and should do many iteratrations to generate style image. How about implement real time style transfer,  what is the main obstacles to achieve that?

**Comment by LouieYang** [comment]
The segmentation of image is for the higher reality of the generated image, you could simply feed with the pure black mask and deal it like normal neural style transfer algorithm which I have not tested yet.

The code need to do iterations on image and could not support real time style transfer. I suggest that you could refer to some fast style transfer papers.

I am new to this field and couldn't point out the obstacles clearly but I recommend one of my supervisors' survey https://github.com/ycjing/Neural-Style-Transfer-Papers. Hope it could help you.

**Comment by lucasjinreal** [comment]
Thanks, many thanks for your advice.

**Comment by ankitesh97** [comment]
How is this achieving general learning? As it is learning on the go (running iterations) for every (content, style) pair?
Thanks

**Comment by LouieYang** [comment]
This work don't support real time style transfer or per-style-per-model. I don't know if it is what you called general learning. @ankitesh97
