### ISSUE TITLE
Style transfer without providing segmentation masks?

### ISSUE THREAD

**Issue by masih4** [LouieYang/deep-photo-styletransfer-tf#12]
Is it possible to use the code without providing segmentation masks?
I tried this but it didn't work:

`python deep_photostyle.py --content_image_path ./examples/input/in11.png - -style_image_path ./examples/style/tar11.png --style_option 1`

**Comment by andrewginns** [comment]
I was able to obtain results without a segmentation mask. Try using a blank png image as the mask that is passed to the program. Results are worse but the transfer is still successful.

**Comment by LouieYang** [comment]
@andrewginns is right, you could use a blank image as the mask and make sure the size of the blank image is the same as the input (for content and style respectively). You can also make some changes on the code that when without providing segmentation mask, it generates blank image itself using functions like `np.zeros_like`

**Comment by masih4** [comment]
Thanks it works now :)
