### ISSUE TITLE
performance time

### ISSUE THREAD

**Issue by bohemetale** [LouieYang/deep-photo-styletransfer-tf#16]
Hi,  I'm running the code on one picture on Tesla K80 (Ubuntu 16 + CUDA 8 + cudann 7 + tensorflow1.4) and 1000 steps takes like 0.5 hour.  
is it normal? 
How much time it takes you to run one example?

**Comment by andrewginns** [comment]
On windows, r1.4 with a 980 it takes me about 8 hours to do a 2000 epoch run. Yours is pretty fast in connection.

**Comment by suke27** [comment]
you take 8hours in inference?
