### ISSUE TITLE
Could you share a baiduyun link of VGG19

### ISSUE THREAD

**Issue by lyycfairy** [LouieYang/deep-photo-styletransfer-tf#17]
as you know，the google drive is not reachable in china

**Comment by LouieYang** [comment]
Updated README, please check the download link

**Comment by lyycfairy** [comment]
thank you @LouieYang
but I failed to download it even if I have installed the Baiduyun client.
and other files seems to be OK.

could you check if the file had been updated successfully , thank you
 
![fail](https://user-images.githubusercontent.com/24890083/35548146-7dcbeb00-05b8-11e8-8c17-cb8747567e1d.png)

**Comment by lyycfairy** [comment]
downloading ,  thank you !
