### ISSUE TITLE
OOM with a GTX 1080 ti

### ISSUE THREAD

**Issue by Hunterwolf88** [LouieYang/deep-photo-styletransfer-tf#19]
Can this actually happen? Am I missing something? Image files are about 2-3 MB,
Used Anaconda environment with Cuda 9.0, CuDNN 7.0, Python 3.6, Tensorflow-gpu 1.7 and all the other libraries up to date.

**Comment by LouieYang** [comment]
Can you pass the test when image files are smaller, like 200-300KB.

**Comment by Hunterwolf88** [comment]
thanks :)
