### ISSUE TITLE
question about getlaplacian

### ISSUE THREAD

**Issue by wanghxcis** [LouieYang/deep-photo-styletransfer-tf#20]
when I set epsilon=1e-6, the affine loss is negative. Is any precision issue with that?

**Comment by LouieYang** [comment]
Yes. I have met the same problem when reproducing. There is a precision issue in [L:31 of closed_form_matting.py](https://github.com/LouieYang/deep-photo-styletransfer-tf/blob/0cce1ef1fc6aa146cbd85285d2ed022ab5c83b91/closed_form_matting.py#L31).

**Comment by wanghxcis** [comment]
Thanks very much for your timely reply.
