### ISSUE TITLE
Option for training from scratch?

### ISSUE THREAD

**Issue by ankitesh97** [LouieYang/deep-photo-styletransfer-tf#23]
Can this code be used for training a new model, for instance if I want to modify the loss term and retrain the model again - is that possible?

Thanks

**Comment by LouieYang** [comment]
Yes, you can modify the loss term and retrain by your own.

**Comment by ankitesh97** [comment]
what file is that?

**Comment by LouieYang** [comment]
photo_style.py

**Comment by ankitesh97** [comment]
thanks :)
