### ISSUE TITLE
Get error when running the command

### ISSUE THREAD

**Issue by Freakwill** [LouieYang/deep-photo-styletransfer-tf#24]
get following error

> Traceback (most recent call last):
>   File "deep_photostyle.py", line 115, in <module>
>     main()
>   File "deep_photostyle.py", line 63, in main
>     best_image_bgr = stylize(args, False)
>   File "/Users/william/Programming/myGithub/deep-photo-styletransfer-tf/photo_style.py", line 231, in stylize
>     vgg_const = Vgg19()
>   File "/Users/william/Programming/myGithub/deep-photo-styletransfer-tf/vgg19/vgg.py", line 16, in __init__
>     self.data_dict = np.load(vgg19_npy_path, encoding='latin1').item()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/lib/npyio.py", line 384, in load
>     fid = open(file, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/william/Programming/myGithub/deep-photo-styletransfer-tf/vgg19/vgg19.npy'

**Comment by LouieYang** [comment]
Please download vgg19.npy file as mentioned in README
