### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by beraybentesen** [LouieYang/deep-photo-styletransfer-tf#3]
File "deep_photostyle.py", line 4, in <module>
    from photo_style import stylize
  File "/home/nvidia/Desktop/Deep-Style-Transfer/deep-photo-styletransfer-tf/photo_style.py", line 6, in <module>
    from vgg19.vgg import Vgg19
ImportError: No module named vgg19.vgg

**Comment by yyll008** [comment]
I have the same error

**Comment by LouieYang** [comment]
Add __init__.py in vgg19 folder, try it again.

**Comment by yyll008** [comment]
Can't solve this

**Comment by LouieYang** [comment]
Really, are you sure you download the latest file and __init__.py is in vgg19 folder?

**Comment by DrewWham** [comment]
I had this problem yesterday and I cloned the repository again today and tried your example code. It is running now. So I think init.py fixed the problem.

**Comment by LouieYang** [comment]
Closed it since __init__.py seems like solving the problem. Maybe [Import a file from a subdirectory?](https://stackoverflow.com/questions/1260792/import-a-file-from-a-subdirectory) could help solving this.

**Comment by yyll008** [comment]
Yes,fixed the problem by init.py
