### ISSUE TITLE
Time taken for one image

### ISSUE THREAD

**Issue by ruthvik92** [LouieYang/deep-photo-styletransfer-tf#31]
Hi,
It takes about 15-20 mins for transferring a style from one image to another content image. I have RTX 2080 SUPER on my laptop, is this normal?  My GPU runs at about 40%. I am trying to do style transfer for my dataset that has 100,000 images and I think I won't be able to do that with this speed. Any suggestions?

**Comment by LouieYang** [comment]
It is actually normal since this work (paper) is just a start-up of so-called "photo style transfer". 

For things you want to do, you can refer to NVIDIA's paper "fast photo style transfer".
