### ISSUE TITLE
No permission to google drive to get the VGG weights

### ISSUE THREAD

**Issue by aviaisr** [LouieYang/deep-photo-styletransfer-tf#32]
How can I get the weights? Google drive link doesn't allow direct downloading.

**Comment by LouieYang** [comment]
Check this [https://drive.google.com/file/d/0BxvKyd83BJjYY01PYi1XQjB5R0E/view?usp=sharing&resourcekey=0-Q2AewV9J7IYVNUDSnwPuCA](url) ?

**Comment by aviaisr** [comment]
Thanks! This link works.
