### ISSUE TITLE
Output image file saving and naming

### ISSUE THREAD

**Issue by DrewWham** [LouieYang/deep-photo-styletransfer-tf#6]
The output iterations seem to be naming themselves based on the total number of iterations not their current iteration. Or maybe I'm doing something wrong. 

python deep_photostyle.py --content_image_path ./Test/input/input.png --style_image_path ./Test/style/style.png --content_seg_path ./Test/segmentation/input_seg.png --style_seg_path ./Test/segmentation/style_seg.png --style_option 2 --max_iter 2000 --save_iter 50 --output_image ./Test/results --lbfgs True --init_image_path ./Test/input/input.png

This results in the first image being named "out_iter_2000.png" and being saved in the working directory I launch python from rather than in the results directory.

**Comment by LouieYang** [comment]
Add `--serial` options, you could now specify a folder to store the temp result. Check it out.

**Comment by DrewWham** [comment]
Awesome, thanks for being so responsive! and I should update, I was wrong about the final save location, that one did end up in the correct spot. Just the iterations and the temp were going to the working directory.
