### ISSUE TITLE
Problem with saving best results under Windows 10.

### ISSUE THREAD

**Issue by Desm0nt** [LouieYang/deep-photo-styletransfer-tf#7]
Windows 10. WinPython 3.5.3 with CUDA, pyCUDA, numpy+mkl, latest tensorflow, etc. CL.exe from MS VS2015 VC++. (pyCUDA setup correctly and successfully run test examples)
When i run programm all seems to be fine: temporary results succesfully saves in result folder, but in the end I got this error:
`Traceback (most recent call last):`
  `File "deep_photostyle.py", line 115, in <module> main()`
 ` File "deep_photostyle.py", line 84, in main
    best_ = smooth_local_affine(output_, input_, 1e-7, 3, H, W, args.f_radius, args.f_edge).transpose(1, 2, 0)`
  `File "D:\WinPython\notebooks\deep-photo-styletransfer\smooth_local_affine.py", line 385, in smooth_local_affine
    np.int32(h), np.int32(w), np.float32(epsilon), np.int32(radius), block=(256, 1, 1), grid=((h * w) / 256 + 1, 1)`
 `File "d:\WinPython\python-3.5.3.amd64\lib\site-packages\pycuda\driver.py", line 402, in function_call
    func._launch_kernel(grid, block, arg_buf, shared, None)`
`TypeError: No registered converter was able to produce a C++ rvalue of type unsigned int from this Python object of type float`

and at the end I have only tmp iteration images, but not a final results.

**Comment by LouieYang** [comment]
Seems like the division `grid=((h * w) / 256 + 1, ...)` has float value returned in python3 while unsigned int value returned in python2.7.

**Comment by yunyezi1** [comment]
I have the same problem, window 10+python3.5+vs2015 vc++, have you get this resolved? Please help! Thanks you.

**Comment by Otherend1** [comment]
Check the other issue, I think I got a fix

**Comment by LouieYang** [comment]
@Otherend1, add it to smooth_local_affine. Thank you again.
